### PR TITLE
Update artman to 0.16.5 in CI

### PR DESCRIPTION
**Pull request by jbolinger**

### CODE REVIEW

**Comment by andreamlin** [comment]
Maybe https://github.com/googleapis/gapic-generator/pull/2501 can fix a little bit of the python failures.

**Comment by andreamlin** [comment]
The python2.7 test fails for me locally on the same error, but the python3.* tests are fine.
@pongad Can you help out on the python ASCII errors?

**Comment by andreamlin** [comment]
@jbolinger Can you take a look at the Ruby failures? there's something about a capitalized letter in Pubsub...

**Comment by jbolinger** [comment]
@andreamlin the Ruby failure is do to a bug in protoc that we just discovered: https://github.com/googleapis/google-cloud-ruby/pull/2782#discussion_r246550700

We'll have to either skip this test or modify the proto (removing the `option ruby_package = ...` line) in order to get it to pass until the underlying issue is fixed. I'm not familiar with how these tests are run. Is there a good place where we could patch the proto before generating the client to remove that line?

**Comment by andreamlin** [comment]
Internal fix for the Python Speech test coming in cl/228612975.

**Comment by andreamlin** [comment]
@jbolinger My lazy preference is to just remove the Ruby Pubsub client generation/testing in CircleCI.

Also filed https://github.com/googleapis/gapic-generator/issues/2503 to track this.

**Comment by jbolinger** [comment]
@andreamlin I think we've got the CI issues worked out. Can you take another look after it finishes (got out of date again)?

**Comment by andreamlin** [comment]
LGTM
haha i am also merging in other changes

**Comment by andreamlin** [comment]
Thanks @jbolinger !

**Pull request merged**
