### PR TITLE
Use artman v0.42.2

### PR DESCRIPTION
**Pull request by alexander-fenster**
Updating the version of `artman` to use in CI.

### CODE REVIEW

**Comment by hzyi-google** [comment]
We need to update protobuf runtime for Java to the same version... I'll open a PR for it.

**Comment by yihanzhen** [comment]
LGTM

**Comment by alexander-fenster** [comment]
@yihanzhen vs @hzyi-google :)

**Comment by hzyi-google** [comment]
Thanks for fixing it though 😝 @alexander-fenster

**Pull request merged**
