### PR TITLE
[bazel] Complete python bazel rules

### PR DESCRIPTION
**Pull request by vam-google**
This adds missing `moved_proto_library` (to repliate path move hack done by artman) and `py_gapic_assembly_pkg` rule (outputs package identical to what artman produces),  making bazel gapic extensions for Python reach feature parity with artman.

This PR depends on https://github.com/googleapis/protoc-docs-plugin/pull/17

### CODE REVIEW

**Comment by vam-google** [comment]
@noahdietz Hm... I think you are right and I should include it in README. I kind of try making it as less visible as possible, because it is an ugly hack. It will be used in the following way (a working example I was testing this stuff on):

```bzl
moved_proto_library(
    name = "firestore_moved_proto",
    srcs = [":firestore_proto"],
    deps = [
        "//google/api:annotations_proto",
        "//google/api:client_proto",
        "//google/rpc:status_proto",
        "//google/type:latlng_proto",
        "@com_google_protobuf//:empty_proto",
        "@com_google_protobuf//:struct_proto",
        "@com_google_protobuf//:timestamp_proto",
        "@com_google_protobuf//:wrappers_proto",
    ],
)

py_proto_library(
    name = "firestore_py_proto",
    deps = [":firestore_moved_proto"],
    plugin = "@protoc_docs_plugin//:docs_plugin",
)

py_grpc_library(
    name = "firestore_py_grpc",
    srcs = [":firestore_moved_proto"],
    deps = [":firestore_py_proto"],
)

py_gapic_library(
    name = "firestore_py_gapic",
    src = ":firestore_proto_with_info",
    gapic_yaml = "firestore_gapic.yaml",
    service_yaml = "//google/firestore:firestore_v1beta1.yaml",
    deps = [
        ":firestore_py_proto",
        ":firestore_py_grpc"
    ],
)
```

**Comment by noahdietz** [comment]
> I kind of try making it as less visible as possible, because it is an ugly hack

Maybe include a _Note:_ explaining that it is a workaround or how you feel about the stability of the target? Especially if you think at some point it will go away.

**Comment by vam-google** [comment]
@noahdietz I updated readme, calling the rule "deprecated" and explaining why it exists. As for point when it goes away - no idea, probably not soon (too much stuff depends on this hack, unfortunately).

**Comment by noahdietz** [comment]
LGTM thanks for adding that!

**Pull request merged**
