### PR TITLE
Remove rogue entrySet call when iterating over maps in C# samples

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by jskeet** [comment]
Hmm... will see if I can work out why the tests are failing.

**Comment by jskeet** [comment]
<sigh> Running the tests on Windows is non-trivial :(

**Comment by jskeet** [comment]
Okay, found a couple more baseline files that contained entrySet. Let's see if this now passes...

**Comment by hzyi-google** [comment]
@jskeet not sure if you are still online since it's already very late in London, I'll go ahead and merge it.

**Comment by jskeet** [comment]
Thanks for merging - still online, but I'm happier for you to merge :)

**Pull request merged**
