### PR TITLE
Add @Generated to generated package-info files

### LINKED ISSUE #1794: java: add @Generated to generated package-info files
It helps automated tools, like ones in https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2763.

The annotation can be added to the `package` statement per [spec](https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html).

### PR DESCRIPTION
**Pull request by xiaozhenliu-gg5**
Add @Generated to package-info.snip
Modify java library baseline to pass tests
Fixes #1794

### CODE REVIEW

**Comment by eoogbe** [comment]
LGTM, but @hzyi-google has more familiarity

**Comment by hzyi-google** [comment]
I think you also need to add `import javax.annotation.Generated` too.

see: https://stackoverflow.com/questions/8405336/how-do-i-add-package-level-annotations-or-edit-package-info-java

**Comment by xiaozhenliu-gg5** [comment]
Thanks Hanzhen, imported @Generated dependency and merged new updates from master.

**Comment by hzyi-google** [comment]
Can you also fix the CLA by following https://github.corp.google.com/prinfo?q=/https://github.com/googleapis/gapic-generator/pull/2879 ?

Feel free to do that after this PR though.

**Pull request merged**
