### PR TITLE
[gapic-gen] fix: generate string overloads for resource names method params

### PR DESCRIPTION
**Pull request by miraleung**
Please see https://github.com/googleapis/gapic-generator/issues/3167 for
more details.

### CODE REVIEW

**Comment by hzyi-google** [comment]
> we declare adding/removing resource name reference to a flattened field as a breaking change

This needs to run through other languages as well.

**Comment by miraleung** [comment]
This currently breaks only vision beta libraries, so if they are OK with these breakages and other languages are fine with this, then that declaration SGTM.

**Comment by vam-google** [comment]
@miraleung I guess braking beta libraries should be Ok, especially if not breaking them is proven to be problematic. 

For the other langauges part, I've clarified with @hzyi-google what he meant by his comment. I guess we need other language owners agree with the "proposal". 

@software-dov 
@chrisdunelm 
@viacheslav-rostovtsev
@noahdietz 
@alexander-fenster  

What do you think if we  **mark adding resource name to a field a potentially breaking change**?

**Comment by chrisdunelm** [comment]
I agree that we should not generate all combinations of string/resource-name parameters. We've definitely need to avoid the 2^n issue.
Simply "declare adding/removing resource name reference to a flattened field as a breaking change" does avoid this, and requires no code changes in any generator.
However, it's less than ideal, and may cause difficulty for API producer teams; as an API grows in size and number of contributors it becomes more likely mistakes will be made.

We should look to see if there's a better solution here, but I agree that in the short-term at least we should make this a breaking change.
As others have said, for a beta release a breaking change like this is generally OK.

**Comment by viacheslav-rostovtsev** [comment]
I agree with Chris above that generating all combinations is a bad solution -- it'll clutter all the APIs unnecessarily. Making it a breaking change seems OK and we can re-address this if it turns out a common re-occuring problem.

**Comment by noahdietz** [comment]
I agree with Chris and Slava, but in practice I don't see it being all that disastrous. In my experience (albeit limited) there are few APIs that have multiple resource_references in a single request message, mainly because RPCs typically work with a single resource (name, parent, etc). The subset that have multiple resource_references and have several such fields included in method_signatures is probably smaller. Although, it might be better to not put ourselves in this position in the first place, because it is very easy to add method_signatures & resource_references and then we start seeing combinatorial explosion. 

Breaking alpha/beta APIs is acceptable if well communicated. I think this (making it a breaking change to add/remove a resource reference to a flattened field) will definitely become an issue if we do not address it soon. We might want to run it by Luke b.c I think other systems might depend on the resource annotations as well.

**Pull request closed without merging**
