### PR TITLE
node: simplify inner call initialization

### PR DESCRIPTION
**Pull request by alexander-fenster**
This PR makes initialization of `this._innerApiCalls` just a little bit more readable by replacing `arguments` with a rest parameter syntax (`...args`). No changes in behavior intended.

Note: more changes to the generation code will follow, this one is just the first and the most minor one.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
👋 I have a petty ask.  Every time we make one of these changes to the generator, it comes with a corresponding 42 PRs by autosynth.  If you expect to line up a few of these ... can we do the work in a branch, and then bring it over to master when ready?  If you're looking to make these small and incremental to reduce risk to the generated libs, that's cool too.  Just looking to optimize for laziness 🙃

**Comment by alexander-fenster** [comment]
Hi @JustinBeckwith! We're going have more of small changes during the upcoming week. I was actually going to be cautious and merge them one by one, but I totally get the idea of minimizing the number of synthtool PRs to merge.

This particular one does not block any of our work (it's just a cosmetic change) so I'm totally fine if it waits for some bigger change to come. For bigger changes such as the upcoming change of the logic of protobuf loading, I'd still ask you to go through all the 42 PRs :)

**Comment by alexander-fenster** [comment]
@bcoe Yes, I verified that it works locally, and the CI passes. This particular piece of generated code is one of the most complicated code snippets in our libraries, so I'm just trying to make it look simpler :)

**Comment by alexander-fenster** [comment]
This is going to be handled in #2888.

**Pull request closed without merging**
