### PR TITLE
fix(PYTHON): update nox file and modernize to new interface

### LINKED ISSUE #2208: Support python3.7 in CircleCI build
The CircleCI build uses docker image googleapis/nox:0.17.0 for running generated unit tests in python. However, this image only contains python 2.7, 3.5, and 3.6, but not 3.7.

The following are possible solutions to support python 3.7:
1. Install python3.7 in the CircleCI job.
2. Figure out how to use the latest googleapis/nox:0.18.2 image with CircleCI workspaces. There is an error when using 0.18.2: https://circleci.com/gh/googleapis/gapic-generator/343.
3. Update the Dockerfile for googleapis/nox from v0.17.0 to include python3.7.

### PR DESCRIPTION
**Pull request by jpoehnelt**
closes #2208, #3157 

This updates to use a recent version of nox. The previous version was nox==0.17.0 from quite some time ago... not even on the changelog https://nox.thea.codes/en/stable/CHANGELOG.html

### CODE REVIEW

**Comment by jpoehnelt** [comment]
I think I am going to abandon this effort to someone else as the tests are a bit daunting to unwind.

**Comment by jpoehnelt** [comment]
looks like this is blocking after all as the noxfile is incompatible with all recent versions of nox

**Comment by jpoehnelt** [comment]
@hzyi-google PTAL :)

**Comment by hzyi-google** [comment]
@software-dov @busunkim96 Can you two take a look?

**Comment by jpoehnelt** [comment]
fyi, I am unable to merge

**Pull request merged**
