### PR TITLE
SampleGen: put PHP samples in the correct directory

### PR DESCRIPTION
**Pull request by hzyi-google**
- Samples now live in `.../google-cloud-language-v1/samples/V1/`.
- Change sample file names to `UpperCamelCase.php`.

### CODE REVIEW

**Comment by hzyi-google** [comment]
=> @googleapis/samplegen 

@beccasaurus as you don't seem to have preference yet whether `samples/` should be under `src/`, I did a wild guess and pulled them out. It makes more sense as they now follow the same pattern as tests :)

We can definitely change if this isn't ideal. Shouldn't be hard at all.

**Comment by hzyi-google** [comment]
@andreamlin Do you mind taking a look as well, as both Michael and Victor are out ;)

**Comment by andreamlin** [comment]
I think the php CircleCI test will sort itself out once the other PR to update the php-gax version is merged in.

**Comment by hzyi-google** [comment]
@andreamlin Yes the diff is just caused by reordering.

**Comment by beccasaurus** [comment]
<3 👍

**Pull request merged**
