### PR TITLE
Adding new --language command-line arg

### PR DESCRIPTION
**Pull request by garrettjonesgoogle**
This is backwards compatible with artman. 

- Plumbing `TargetLanguage` throughout the code
- Removing the "generator id" concept altogether.
  - Node: using the NODEJS_DOC codepath; updating the Node baselines to reflect generation of docs
  - Ruby: using the RUBY_DOC codepath; updating the Ruby baselines to reflect generation of docs
- Deleting `GapicGeneratorConfig`, passing around its components instead
- Deleting CLIENT_CONFIG support - Artman doesn't use it, and all relevant languages perform the same generation anyway

### CODE REVIEW

**Comment by garrettjonesgoogle** [comment]
cc @andreamlin (for discogapic changes), cc @jbolinger (for Ruby changes - FYI only, it shouldn't change real API generation output), cc @alexander-fenster (for NodeJS changes - FYI only, it shouldn't change real API generation output)

**Comment by michaelbausor** [comment]
Changes LGTM, but I didn't get why the baselines need to be renamed, and why there were changes in ruby and node?

**Comment by alexander-fenster** [comment]
LGTM from my side, let's see :)

**Comment by garrettjonesgoogle** [comment]
I decided to re-enable sample test generation within the baseline tests (it will stay off for real generation, which is the status quo)

**Pull request merged**
