### PR TITLE
use latest artman in smoketest

### PR DESCRIPTION
**Pull request by hzyi-google**
Hopefully this fixes the failures of artman smoke tests.

### CODE REVIEW

**Comment by hzyi-google** [comment]
Hey @alexander-fenster does artman smoke test only runs on master but not on PRs? Is there a way I could verify the fix works before merging?

**Comment by alexander-fenster** [comment]
@hzyi-google To verify that, temporarily remove the branch filter in CircleCI config.  I'll comment it out, please make sure to enable it back before merging :)

**Comment by alexander-fenster** [comment]
@hzyi-google https://circleci.com/workflow-run/eaab0979-0b07-4324-a391-e8c1ace8f606 is the workflow I started.

**Comment by hzyi-google** [comment]
@alexander-fenster it looks the tests passed (yay). I will uncomment the branch filter now.

**Pull request merged**
