### PR TITLE
Samplegen: print enums in PHP

### PR DESCRIPTION
**Pull request by hzyi-google**

### CODE REVIEW

**Comment by hzyi-google** [comment]
PTAL @vchudnov-g @michaelbausor @beccasaurus

**Comment by michaelbausor** [comment]
Using the new `::name` methods on enums is definitely what we want to do - but there isn't a released version of protobuf that includes them yet, so we will need to wait for protobuf 3.7 I think.

**Comment by hzyi-google** [comment]
@michaelbausor Can we just leave this PR open until protobuf 3.7 is out?

**Comment by michaelbausor** [comment]
Yes, we can. I don't know what time frame is expected for protobuf 3.7, but I think it is coming fairly soon.

**Comment by vchudnov-g** [comment]
@michaelbausor Do you have any sense on what "soon" is? Early January? EOQ1?

**Comment by michaelbausor** [comment]
The current latest I heard from them is ~early January.

**Comment by beccasaurus** [comment]
From the Protobuf issue:

> 3.7.0rc2 should already have this [`*`](https://github.com/protocolbuffers/protobuf/pull/5342#issuecomment-464773459)

Do our client libraries (PHP) use `rc` versions of Protobuf? I'm guessing not, but want to check before asking Protobuf if they know when `3.7` stable will be released.

Looks like this'll work now, but only using the latest `rc2`

**Comment by michaelbausor** [comment]
@beccasaurus Protobuf 3.7 is out! https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.0

**Comment by hzyi-google** [comment]
Ah thanks! This PR has become a bit outdated though, I'm gonna close it here and create a new one.

**Pull request closed without merging**
