### PR TITLE
Revert "Python: use 'ProtoFiles.getProtoFiles' to sort enums by filename."

### PR DESCRIPTION
**Pull request by tseaver**
Reverts googleapis/gapic-generator#2418

See: #2429.

### CODE REVIEW

**Comment by andreamlin** [comment]
Are able to use this change in a local fork of gapic-generator to generate the desired Bigtable's python client?

**Comment by tseaver** [comment]
@andreamlin 

> Are able to use this change in a local fork of gapic-generator to generate the desired Bigtable's python client?

I don't have enough knowledge of the toolchain to figure that out:  I'm just backing the change out because the bug appeared to occur after the change from #2418 was propagated to the artman image.

**Comment by tseaver** [comment]
@andreamlin Should I close this PR, given your change in #2440?

**Comment by andreamlin** [comment]
@tseaver right now i'll generate the python client with and without my change, and see if it the fix fixes this

**Comment by andreamlin** [comment]
Verified locally that without this PR (the reverting PR), the `StorageType` class (from the linked bigtable synth PR) is not generated in the Python client, and with this PR, artman will generate the `StorageType` class. Therefore, we should check in this PR.

Thanks a lot for opening this reverting PR!

**Pull request merged**
