### PR TITLE
Example of *not* escaping lang_doc string

### PR DESCRIPTION
**Pull request by andreamlin**
We can un-escape YAML special chars by putting them in single-quotes.

By following this example, we should be able to fix pubsub_gapic.yaml and close out https://github.com/googleapis/gapic-generator/issues/937

The resulting `@ literal @` is kinda weird but it's in line with the rendering in https://github.com/googleapis/gapic-generator/blob/580c79d8aecadd5f401b9a333c76af7c7f381907/src/test/java/com/google/api/codegen/gapic/testdata/java/java_library.baseline#L3918

### CODE REVIEW

**Comment by andreamlin** [comment]
PTAL

**Comment by pongad** [comment]
I think you got the issue backwards. I think we should be able to *not* escape. Eg, if we actually want to insert a `@See This.Other.Class` in the Javadoc, we should be able to.

**Comment by andreamlin** [comment]
@pongad whoops yes fixed title. 
The content of the PR is not backwards tho is it?

**Comment by pongad** [comment]
I think it is right? It's a little confusing to explain, so let me know if you want to follow up on IM.

But imagine what you might do if you actually want to insert a link in the Javadoc. If you're editing the Javadoc directly, you might write `@see the.Class`. But writing that in `lang_doc` doesn't create a link, it writes `{@literal @}see the.Class` which renders `@see the.Class`. Am I making this more confusing? :rofl:

**Comment by andreamlin** [comment]
@pongad I am confused, yes. How is this different from 
```
 *         {@literal @}Override
```
in the generated method comment?

**Comment by vchudnov-g** [comment]
I'm lacking context on this PR. Why do you have a PR exemplifying how **not** to escape?

Not an expert on javadoc, but it seems to me the output in the baselines is not what we want: we do want the `{@see everywhere}` just copied from the config, right? Is there a reason we cant just copy it?

Again, I'm probably missing the context/motivation for this PR.

**Comment by vchudnov-g** [comment]
No action on this, not sure we need it. Closing for now.

fyi: @hzyi-google

**Pull request closed without merging**
