### PR TITLE
[node] Use var instead of const when value changes

### PR DESCRIPTION
**Pull request by andreamlin**
Fixes https://github.com/googleapis/gapic-generator/issues/2282.

### CODE REVIEW

**Comment by andreamlin** [comment]
This PR is merged into https://github.com/googleapis/gapic-generator/pull/2251, which shows [passing](https://circleci.com/gh/googleapis/gapic-generator/2466) logging and speech tests, as opposed to the TypeError thrown in https://circleci.com/gh/googleapis/gapic-generator/2430

**Comment by andreamlin** [comment]
Travis build is broken because of https://github.com/travis-ci/travis-ci/issues/10053.

**Comment by andreamlin** [comment]
PTAL

**Comment by alexander-fenster** [comment]
@JustinBeckwith not all `const` are in fact `const` :)

**Comment by JustinBeckwith** [comment]
Ooooops!  Nice catch :) Thanks for the speedy fix!

**Pull request merged**
