### PR TITLE
Create a new ClientInfo if none is provided.

### LINKED ISSUE #2161: Create new instance of client info rather than stomping on shared instance.
While reviewing a new client @tseaver noticed a bit that may need revising. 

Quoting from https://github.com/GoogleCloudPlatform/google-cloud-python/pull/5665/files/12676aaf08dc795f2216f9441896cfae54edd382#diff-198e257d2c267a0bc3e3d2f3e77ec561

 https://github.com/GoogleCloudPlatform/google-cloud-python/blob/master/dlp/google/cloud/dlp_v2/gapic/dlp_service_client.py#L173
```python
        if client_info is None:
            client_info = (
                google.api_core.gapic_v1.client_info.DEFAULT_CLIENT_INFO)
        client_info.gapic_version = _GAPIC_LIBRARY_VERSION
```

This bit is problematic -- the `DEFAULT_CLIENT_INFO` instance is going to be scribbled on by every library generated this way, which means that each time an app instantiates a generated client, they *all* use the last-instantiated one's `gapic_version`.

Rather than reuse the instance, we should be constructing a *new* one here, e.g.:

```python
        if client_info is None:  # create a new instance
            client_info = (
                google.api_core.gapic_v1.client_info.ClientInfo(
                    gapic_version=_GAPIC_LIBRARY_VERSION)
        else:  # update caller-supplied instance
            client_info.gapic_version = _GAPIC_LIBRARY_VERSION
```

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes #2161.

### CODE REVIEW

**Comment by michaelbausor** [comment]
Ping on this - can it be merged?

**Comment by tseaver** [comment]
@lukesneeringer Ping?

**Comment by tseaver** [comment]
@lukesneeringer Ping?

**Comment by theacodes** [comment]
@googleapis/api-compiler can someone look at this? It's still a problem for us.

**Comment by theacodes** [comment]
@googleapis/toolchain can someone look at this? It's still a problem for us.

**Pull request merged**
