### PR TITLE
Fix Python snippet bug

### PR DESCRIPTION
**Pull request by andreamlin**
Fixes https://github.com/googleapis/gapic-generator/issues/2422.

### CODE REVIEW

**Comment by andreamlin** [comment]
PTAL

**Comment by landrito** [comment]
I think the correct way to document this is like: 

```
:meth:`method_name`
```

**Comment by andreamlin** [comment]
@landrito ok, using the Sphinx syntax for method referencing. Also qualifying the method reference by the class that contains the method
PTAL

**Comment by andreamlin** [comment]
@crwilcox would you mind reviewing this too?

**Comment by andreamlin** [comment]
The Ruby test has been chronically failing https://github.com/googleapis/gapic-generator/issues/2458

**Comment by andreamlin** [comment]
PTAL

**Comment by landrito** [comment]
Bah sorry, since the transport should be agnostic to the client that is using it, I think simply using the method name without the fancy linking syntax is best.

**Pull request merged**
