### PR TITLE
go: don't generate empty LRO Metadata()

### PR DESCRIPTION
**Pull request by pongad**
Most methods we generate have signatures like this:

  func (*Client) Method(context.Context, *pb.Request) (*pb.Response, error)

If the response is an empty type, it's not terribly useful, so we drop
it, making the signature:

  func (*Client) Method(context.Context, *pb.Request) error

Since we never write the name of the Empty type,
we have a special logic to never import the "emptypb" package
so we don't get the imported-but-not-used error.

The problem is that if a long-running operation has an Empty metadata,
we still create the

  func (*Operation) Metadata() (*emptypb.Empty, error)

method. This does not compile, because now we're using emptypb without
importing.

The solution is to simply not generating the Metadata() method at all,
since it doesn't contain any useful information anyway.

### CODE REVIEW

**Comment by pongad** [comment]
@garrettjonesgoogle @lukesneeringer Do you think it's worth adding a whole new baseline for this? Do other langs have special treatment for empty?

**Comment by jadekler** [comment]
This is technically breaking the API surface of many clients, right? Is there any possible use of metadata at all? Does the error return anything useful - can it be used as a hacky ping or something?

**Comment by jba** [comment]
@jadekler You're right, it is a breaking change, but it's unlikely anyone is using the method because it's useless.

**Comment by pongad** [comment]
In some ways, it's not breaking because the current code won't compile :laughing:

**Pull request merged**
